sudo: required
services:
    - docker

before_install:
    - docker build -t willasv/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true willasv/react-test npm test -- --coverage

after_success:
    - docker build -t willasv/enterprise-fibonacci-client ./client
    - docker build -t willasv/enterprise-fibonacci-nginx ./nginx
    - docker build -t willasv/enterprise-fibonacci-server ./server
    - docker build -t willasv/enterprise-fibonacci-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push willasv/enterprise-fibonacci-client
    - docker push willasv/enterprise-fibonacci-nginx
    - docker push willasv/enterprise-fibonacci-server
    - docker push willasv/enterprise-fibonacci-worker