version: '3'
services: # service names are hostnames
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    api:
        depends_on:
            - postgres
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules #leave as is
            - ./server:/app #when trying to access app folder, use server folder on host
        environment: 
            - REDIS_HOST=redis #hostname in this config
            - REDIS_PORT=6379
            - PG_HOST=postgres 
            - PG_USER=postgres
            - PG_PASSWORD=*#postgreS9009#*
            - PG_DATABASE=enterprisefibonacci
            - PG_PORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'